
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class agent_instance
{

    public System.Guid id { get; set; }

    public System.Guid agentid { get; set; }

    public Nullable<System.DateTime> lastalivetime { get; set; }

    public string version { get; set; }



    public virtual agent agent { get; set; }

}

}
