
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class agent_version
{

    public int Id { get; set; }

    public string Version { get; set; }

    public System.DateTime ExpiresOn { get; set; }

    public string Comment { get; set; }

}

}
