//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agent()
        {
            this.agent_instance = new HashSet<agent_instance>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public Nullable<System.Guid> subscriptionid { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> lastalivetime { get; set; }
        public bool is_on_premise { get; set; }
        public string version { get; set; }
        public byte[] password_hash { get; set; }
        public byte[] password_salt { get; set; }
    
        public virtual subscription subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<agent_instance> agent_instance { get; set; }
    }
}
