
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ceremony
{

    public short OrderID { get; set; }

    public Nullable<short> CeremonyLocationID { get; set; }

    public Nullable<System.DateTime> CeremonyDateTime { get; set; }

    public string CeremonyNotes { get; set; }

    public Nullable<short> CommittalLocationID { get; set; }

    public Nullable<System.DateTime> CommitalDateTime { get; set; }

    public string CommittalNotes { get; set; }

    public string ReceptionAddress1 { get; set; }

    public string ReceptionAddress2 { get; set; }

    public string ReceptionCity { get; set; }

    public string ReceptionPostCode { get; set; }

    public Nullable<System.DateTime> ReceptionDateTime { get; set; }

    public string ReceptionNotes { get; set; }

    public byte OfficiantID { get; set; }

    public string OfficiantNotes { get; set; }



    public virtual CommittalLocation CommittalLocation { get; set; }

    public virtual CommittalLocation CommittalLocation1 { get; set; }

    public virtual Officiant Officiant { get; set; }

    public virtual Order Order { get; set; }

}

}
