//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeceasedContact
    {
        public short DeceasedID { get; set; }
        public int ID { get; set; }
        public byte ContactTypeID { get; set; }
        public string Title { get; set; }
        public string Forenames { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Occupation { get; set; }
        public string Relationship { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public bool ConsentToBeContacted { get; set; }
        public bool AccountModerator { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> DoctorID { get; set; }
    
        public virtual Deceased Deceased { get; set; }
        public virtual DeceasedContactsContactType DeceasedContactsContactType { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
