
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Deceased
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Deceased()
    {

        this.DeceasedAddresses = new HashSet<DeceasedAddress>();

        this.DeceasedContacts = new HashSet<DeceasedContact>();

        this.Orders = new HashSet<Order>();

    }


    public short ID { get; set; }

    public string Title { get; set; }

    public string Fornames { get; set; }

    public string Surname { get; set; }

    public string KnownAs { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public byte Age { get; set; }

    public string Gender { get; set; }

    public System.DateTime DateTimeOfDeath { get; set; }

    public string Occupation { get; set; }

    public string Length { get; set; }

    public string Width { get; set; }

    public string Depth { get; set; }

    public Nullable<byte> MaritalStatusID { get; set; }

    public Nullable<int> DenominationID { get; set; }

    public System.DateTime CreationTime { get; set; }

    public byte CreatedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedTime { get; set; }

    public Nullable<byte> LastModifiedBy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeceasedAddress> DeceasedAddresses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeceasedContact> DeceasedContacts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order> Orders { get; set; }

    public virtual ReligiousDenomination ReligiousDenomination { get; set; }

    public virtual MaritalStatu MaritalStatu { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
