
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Memorial
{

    public short OrderID { get; set; }

    public string Requirement { get; set; }

    public Nullable<bool> MemorialBooked { get; set; }

    public Nullable<bool> MemorialRemovalBooked { get; set; }

    public string Material { get; set; }

    public string Finish { get; set; }

    public Nullable<System.DateTime> FixingDate { get; set; }

    public string MasonryQuoteRef { get; set; }

    public string InscriptionText { get; set; }

    public string InscriptionFont { get; set; }

    public string InscriptionFinish { get; set; }

    public string Base { get; set; }

    public string Size { get; set; }

    public Nullable<bool> PhotoTaken { get; set; }

    public string Desc { get; set; }

    public bool AshesIntermentReq { get; set; }



    public virtual MemorialContactPoint MemorialContactPoint { get; set; }

    public virtual Order Order { get; set; }

}

}
