//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageQueue
    {
        public System.Guid MessageId { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public int MessageType { get; set; }
        public string MessageData { get; set; }
        public System.DateTime InitialInsertTimeUTC { get; set; }
        public System.DateTime InsertTimeUTC { get; set; }
        public Nullable<System.DateTime> UpdateTimeUTC { get; set; }
        public byte ExecTimes { get; set; }
        public int ResetTimes { get; set; }
        public long Version { get; set; }
        public Nullable<System.Guid> TracingId { get; set; }
        public Nullable<System.Guid> QueueId { get; set; }
        public Nullable<System.Guid> WorkerId { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
