//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaInformation
    {
        public int Id { get; set; }
        public int VersionMajor { get; set; }
        public int VersionMinor { get; set; }
        public int VersionBuild { get; set; }
        public int VersionService { get; set; }
        public string VersionString { get; set; }
        public Nullable<long> Version { get; set; }
        public bool State { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
