
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Notification
{

    public byte UserID { get; set; }

    public int ID { get; set; }

    public string Details { get; set; }

    public string Category { get; set; }

    public Nullable<byte> NotificationFrom { get; set; }

    public string MVCAction { get; set; }

    public string MVCController { get; set; }

    public string MVCParam { get; set; }

    public System.DateTime TimeLogged { get; set; }



    public virtual User User { get; set; }

}

}
