
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OrderChecklist
{

    public short OrderID { get; set; }

    public byte HospitalReleaseFormRecieved { get; set; }

    public byte DeceasedBroughtIntoCare { get; set; }

    public byte FuneralArrangementComplete { get; set; }

    public byte ItinerarySentToClient { get; set; }

    public byte CremCertificateRecieved { get; set; }

    public byte CremationBooked { get; set; }

    public byte OfficiantConfirmationSent { get; set; }

    public byte CremForm1Complete { get; set; }

    public byte CremForm2Complete { get; set; }

    public byte CremForm3Complete { get; set; }

    public byte CremFormsDelivered { get; set; }

    public byte CrematedRemainsInstructionsRecieved { get; set; }

    public byte ArrangementSignedAndUploaded { get; set; }

    public byte CoffinOrderPlace { get; set; }

    public byte CoffinRecievedAndFitted { get; set; }

    public byte ClientAdvisedVisitingIsReady { get; set; }

    public byte OrganistMusicConfirmed { get; set; }

    public byte FlowersOrdered { get; set; }

    public byte OrderOfServiceApproved { get; set; }

    public byte OrderOfServicePrinted { get; set; }

    public byte ObirAgreedAndSubmitted { get; set; }



    public virtual Order Order { get; set; }

}

}
