
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {

        this.Jewelleries = new HashSet<Jewellery>();

        this.Musics = new HashSet<Music>();

        this.OrderItems = new HashSet<OrderItem>();

        this.Organists = new HashSet<Organist>();

        this.Transports = new HashSet<Transport>();

        this.Visitors = new HashSet<Visitor>();

    }


    public short ID { get; set; }

    public short ClientID { get; set; }

    public short DeceasedID { get; set; }

    public byte OrderTypeID { get; set; }

    public byte OrderSubTypeID { get; set; }

    public byte OrderStatusID { get; set; }

    public byte OrderSubStatusID { get; set; }

    public System.DateTime CreationTime { get; set; }

    public byte CreatedBy { get; set; }

    public Nullable<System.DateTime> LastModifiedTime { get; set; }

    public Nullable<byte> LastModifiedBy { get; set; }



    public virtual Ceremony Ceremony { get; set; }

    public virtual Client Client { get; set; }

    public virtual Deceased Deceased { get; set; }

    public virtual Memorial Memorial { get; set; }

    public virtual OrderChecklist OrderChecklist { get; set; }

    public virtual OrderCost OrderCost { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Jewellery> Jewelleries { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Music> Musics { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderItem> OrderItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Organist> Organists { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transport> Transports { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Visitor> Visitors { get; set; }

    public virtual OrderStatu OrderStatu { get; set; }

    public virtual OrderSubStatu OrderSubStatu { get; set; }

    public virtual OrderSubType OrderSubType { get; set; }

    public virtual OrderType OrderType { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
