
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ScheduleTask1
{

    public System.Guid ScheduleTaskId { get; set; }

    public int TaskType { get; set; }

    public string TaskName { get; set; }

    public Nullable<int> Schedule { get; set; }

    public int State { get; set; }

    public System.DateTime NextRunTime { get; set; }

    public Nullable<System.Guid> MessageId { get; set; }

    public string TaskInput { get; set; }

    public System.Guid QueueId { get; set; }

    public System.Guid TracingId { get; set; }

    public System.Guid JobId { get; set; }



    public virtual Schedule Schedule1 { get; set; }

}

}
