//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncgroupmember
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string scopename { get; set; }
        public System.Guid syncgroupid { get; set; }
        public int syncdirection { get; set; }
        public System.Guid databaseid { get; set; }
        public int memberstate { get; set; }
        public int hubstate { get; set; }
        public System.DateTime memberstate_lastupdated { get; set; }
        public System.DateTime hubstate_lastupdated { get; set; }
        public Nullable<System.DateTime> lastsynctime { get; set; }
        public Nullable<System.DateTime> lastsynctime_zerofailures_member { get; set; }
        public Nullable<System.DateTime> lastsynctime_zerofailures_hub { get; set; }
        public Nullable<System.Guid> jobId { get; set; }
        public Nullable<System.Guid> hubJobId { get; set; }
        public bool noinitsync { get; set; }
        public Nullable<bool> memberhasdata { get; set; }
    
        public virtual syncgroup syncgroup { get; set; }
        public virtual userdatabase userdatabase { get; set; }
    }
}
