
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Transport
{

    public short OrderID { get; set; }

    public byte LineItem { get; set; }

    public int TransportTypeID { get; set; }

    public string Vehicle { get; set; }

    public short SupplierID { get; set; }

    public Nullable<System.DateTime> PickupTime { get; set; }

    public string CollectionAddress1 { get; set; }

    public string CollectionAddress2 { get; set; }

    public string CollectionCity { get; set; }

    public string CollectionPostCode { get; set; }

    public string Destination1Address1 { get; set; }

    public string Destination1Address2 { get; set; }

    public string Destination1City { get; set; }

    public string Destination1PostCode { get; set; }

    public string Destination2Address1 { get; set; }

    public string Destination2Address2 { get; set; }

    public string Destination2City { get; set; }

    public string Destination2Postcode { get; set; }

    public string ReturnAddress1 { get; set; }

    public string ReturnAddress2 { get; set; }

    public string ReturnCity { get; set; }

    public string ReturnPostCode { get; set; }



    public virtual Order Order { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual TransportType TransportType { get; set; }

}

}
