
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class userdatabase
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public userdatabase()
    {

        this.syncgroups = new HashSet<syncgroup>();

        this.syncgroupmembers = new HashSet<syncgroupmember>();

    }


    public System.Guid id { get; set; }

    public string server { get; set; }

    public string database { get; set; }

    public int state { get; set; }

    public System.Guid subscriptionid { get; set; }

    public System.Guid agentid { get; set; }

    public byte[] connection_string { get; set; }

    public string db_schema { get; set; }

    public bool is_on_premise { get; set; }

    public string sqlazure_info { get; set; }

    public Nullable<System.DateTime> last_schema_updated { get; set; }

    public Nullable<System.DateTime> last_tombstonecleanup { get; set; }

    public string region { get; set; }

    public Nullable<System.Guid> jobId { get; set; }



    public virtual subscription subscription { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<syncgroup> syncgroups { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<syncgroupmember> syncgroupmembers { get; set; }

}

}
