
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vw_GetDeceasedProfile
{

    public short Reference { get; set; }

    public string Title { get; set; }

    public string Forenames { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public Nullable<System.DateTime> DOB { get; set; }

    public string Known_As { get; set; }

    public byte Age { get; set; }

    public string Gender { get; set; }

    public System.DateTime TimeOfDeath { get; set; }

    public string Religion { get; set; }

    public string ReligiousDenomination { get; set; }

    public string MaritalStatus { get; set; }

    public string Occupation { get; set; }

}

}
