
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ECMills.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vw_GetUserNotifications
{

    public byte UserID { get; set; }

    public int ID { get; set; }

    public string Details { get; set; }

    public string Category { get; set; }

    public string NotificationFrom { get; set; }

    public string Controller { get; set; }

    public string Action { get; set; }

    public string Param { get; set; }

    public System.DateTime TimeLogged { get; set; }

}

}
