//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetDeceasedList
    {
        public short Reference { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
        public string Status { get; set; }
        public string Deceased_Name { get; set; }
        public string Client_Name { get; set; }
    }
}
